# Generated by Django 6.0 on 2025-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffein_level', models.TextField(max_length=255)),
                ('theme', models.TextField(max_length=255)),
                ('taste_type', models.TextField(max_length=255)),
                ('tea_type', models.TextField(max_length=255)),
                ('additive', models.TextField(max_length=255)),
                ('price_range', models.IntegerField()),
            ],
            options={
                'db_table': 'users_requests',
            },
        ),
    ]
