# Generated by Django 6.0 on 2026-01-10 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_functionality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'additives',
            },
        ),
        migrations.CreateModel(
            name='BaseTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'base_tastes',
            },
        ),
        migrations.CreateModel(
            name='BaseTea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tea_type', models.CharField(max_length=255)),
                ('making_time', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'base_teas',
            },
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tastes',
            },
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='additive',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='coffein_level',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='no_additives',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='taste_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='tea_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='theme',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Subtaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_taste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functionality.basetaste')),
            ],
            options={
                'db_table': 'subtastes',
            },
        ),
        migrations.CreateModel(
            name='SubtasteAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functionality.additive')),
                ('subtaste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functionality.subtaste')),
            ],
            options={
                'db_table': 'subtastes_tastes',
            },
        ),
        migrations.CreateModel(
            name='BaseTeaTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functionality.basetea')),
                ('taste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functionality.taste')),
            ],
            options={
                'db_table': 'base_teas_tastes',
            },
        ),
        migrations.AddField(
            model_name='basetea',
            name='tastes',
            field=models.ManyToManyField(through='main_functionality.BaseTeaTaste', to='main_functionality.taste'),
        ),
        migrations.CreateModel(
            name='TasteSubtaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtaste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functionality.subtaste')),
                ('taste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functionality.taste')),
            ],
            options={
                'db_table': 'tea_taste_mappings',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('additives', models.ManyToManyField(related_name='themes', to='main_functionality.additive')),
                ('subtastes', models.ManyToManyField(related_name='themes', to='main_functionality.subtaste')),
            ],
            options={
                'db_table': 'themes',
            },
        ),
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('additives', models.ManyToManyField(blank=True, related_name='blends', to='main_functionality.additive')),
                ('teas', models.ManyToManyField(related_name='blends', to='main_functionality.basetea')),
                ('subtaste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_functionality.subtaste')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_functionality.theme')),
            ],
            options={
                'db_table': 'blends',
            },
        ),
        migrations.AddConstraint(
            model_name='subtaste',
            constraint=models.UniqueConstraint(fields=('name', 'base_taste'), name='subtastes_basetaste_fk'),
        ),
        migrations.AddConstraint(
            model_name='subtasteadditive',
            constraint=models.UniqueConstraint(fields=('subtaste', 'additive'), name='subtastes_additive_fk'),
        ),
        migrations.AddConstraint(
            model_name='baseteataste',
            constraint=models.UniqueConstraint(fields=('tea', 'taste'), name='tea_taste_fk'),
        ),
        migrations.AddConstraint(
            model_name='tastesubtaste',
            constraint=models.UniqueConstraint(fields=('taste', 'subtaste'), name='taste_subtaste_fk'),
        ),
    ]
